<a href="https://colab.research.google.com/github/12-Teresa-py/Data-Science/blob/main/social_media_and_mental_wellbeing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#PANDAS (DAY 1)

In [ ]:
!pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
import pandas as pd

In [ ]:
pd.__version__

'2.2.2'

In [ ]:
df = pd.read_csv("/content/social_media_addiction_mental_wellbeing.csv")
df.head()

,User_ID,Age,Gender,Occupation,Relationship_Status,Primary_Platform,Daily_Usage_Hours,Platforms_Used_Count,Posts_Per_Week,Late_Night_Usage,...,Loneliness_Score,Self_Esteem_Score,Sleep_Quality_Score,Sleep_Hours,Productivity_Loss_Score,Offline_Relationship_Quality,Physical_Activity_Hrs_Week,Screen_Free_Time_Hrs,Mental_Wellbeing_Score,Addiction_Level
0,USR00001,30,Male,Working Professional,In a Relationship,YouTube,2.9,4,3,No,...,1.7,6.5,8.5,5.3,3.7,3.8,5.8,3.1,7.3,Low
1,USR00002,19,Male,Student,Married,Instagram,4.8,1,0,NaN,...,7.0,7.5,7.8,5.5,4.0,1.8,0.9,3.3,4.1,Severe
2,USR00003,40,Male,Student,In a Relationship,YouTube,NaN,4,5,No,...,5.6,5.3,6.3,NaN,5.8,2.8,0.0,1.5,5.6,High
3,USR00004,37,Female,Student,Married,Facebook,7.7,2,3,Yes,...,5.6,1.4,3.9,6.1,5.5,3.6,1.0,3.9,4.3,Severe
4,USR00005,18,Non-binary,Student,In a Relationship,TikTok,4.6,3,0,No,...,4.0,NaN,5.7,5.0,3.8,3.2,0.6,1.0,6.6,Moderate

In [ ]:
df.tail()

,User_ID,Age,Gender,Occupation,Relationship_Status,Primary_Platform,Daily_Usage_Hours,Platforms_Used_Count,Posts_Per_Week,Late_Night_Usage,...,Loneliness_Score,Self_Esteem_Score,Sleep_Quality_Score,Sleep_Hours,Productivity_Loss_Score,Offline_Relationship_Quality,Physical_Activity_Hrs_Week,Screen_Free_Time_Hrs,Mental_Wellbeing_Score,Addiction_Level
1495,USR01496,40,Male,Working Professional,In a Relationship,TikTok,2.7,2,4,No,...,3.3,7.4,8.5,6.7,4.5,7.6,2.3,2.3,6.5,High
1496,USR01497,23,Non-binary,Student,Married,YouTube,3.5,3,6,Yes,...,4.2,1.9,7.2,6.9,7.2,NaN,2.8,2.0,6.4,Moderate
1497,USR01498,39,Female,Student,Single,Instagram,5.3,2,3,Yes,...,0.4,2.4,5.1,NaN,6.4,7.8,2.6,4.8,4.7,Severe
1498,USR01499,26,Female,Freelancer,Single,Twitter/X,7.3,4,0,Yes,...,7.5,6.6,6.4,4.2,9.1,6.4,3.6,2.1,6.4,High
1499,USR01500,16,Female,Working Professional,In a Relationship,TikTok,0.7,3,2,No,...,5.9,8.5,5.3,7.2,3.4,2.3,3.9,3.1,6.1,Moderate

In [ ]:
df.head(10)

,User_ID,Age,Gender,Occupation,Relationship_Status,Primary_Platform,Daily_Usage_Hours,Platforms_Used_Count,Posts_Per_Week,Late_Night_Usage,...,Loneliness_Score,Self_Esteem_Score,Sleep_Quality_Score,Sleep_Hours,Productivity_Loss_Score,Offline_Relationship_Quality,Physical_Activity_Hrs_Week,Screen_Free_Time_Hrs,Mental_Wellbeing_Score,Addiction_Level
0,USR00001,30,Male,Working Professional,In a Relationship,YouTube,2.9,4,3,No,...,1.7,6.5,8.5,5.3,3.7,3.8,5.8,3.1,7.3,Low
1,USR00002,19,Male,Student,Married,Instagram,4.8,1,0,NaN,...,7.0,7.5,7.8,5.5,4.0,1.8,0.9,3.3,4.1,Severe
2,USR00003,40,Male,Student,In a Relationship,YouTube,NaN,4,5,No,...,5.6,5.3,6.3,NaN,5.8,2.8,0.0,1.5,5.6,High
3,USR00004,37,Female,Student,Married,Facebook,7.7,2,3,Yes,...,5.6,1.4,3.9,6.1,5.5,3.6,1.0,3.9,4.3,Severe
4,USR00005,18,Non-binary,Student,In a Relationship,TikTok,4.6,3,0,No,...,4.0,NaN,5.7,5.0,3.8,3.2,0.6,1.0,6.6,Moderate
5,USR00006,34,Male,Working Professional,Married,YouTube,1.2,1,3,No,...,5.0,7.9,NaN,5.6,2.8,5.6,4.1,1.5,7.7,Low
6,USR00007,38,Female,Student,In a Relationship,Facebook,5.0,4,4,Yes,...,7.2,0.5,4.8,8.2,6.8,5.4,3.2,3.7,5.5,High
7,USR00008,22,Female,Unemployed,Single,Twitter/X,3.4,5,2,No,...,3.1,2.9,3.8,10.0,6.8,6.7,NaN,6.6,6.2,Moderate
8,USR00009,43,Female,Student,Single,YouTube,9.2,4,2,No,...,3.8,5.1,3.2,5.7,3.2,5.4,4.8,0.6,3.4,Severe
9,USR00010,40,Male,Student,Single,Instagram,6.9,2,5,Yes,...,3.9,8.1,7.4,5.8,6.4,7.2,4.6,0.0,7.7,Low

In [ ]:
df.tail(12)

,User_ID,Age,Gender,Occupation,Relationship_Status,Primary_Platform,Daily_Usage_Hours,Platforms_Used_Count,Posts_Per_Week,Late_Night_Usage,...,Loneliness_Score,Self_Esteem_Score,Sleep_Quality_Score,Sleep_Hours,Productivity_Loss_Score,Offline_Relationship_Quality,Physical_Activity_Hrs_Week,Screen_Free_Time_Hrs,Mental_Wellbeing_Score,Addiction_Level
1488,USR01489,22,Female,Student,Single,Facebook,3.2,5,6,Yes,...,4.5,7.1,7.2,5.9,6.2,2.9,0.5,0.2,6.2,Moderate
1489,USR01490,26,Female,Student,Married,Snapchat,5.0,2,5,No,...,6.0,2.5,8.4,5.5,NaN,3.6,5.9,5.3,7.3,Low
1490,USR01491,31,Female,Student,Single,Twitter/X,6.9,2,2,Yes,...,6.0,5.4,2.2,5.6,5.2,6.0,2.2,2.9,5.9,High
1491,USR01492,21,Non-binary,Student,Single,Instagram,5.1,3,3,No,...,3.2,6.2,4.7,6.5,2.5,8.5,0.5,4.7,9.3,Low
1492,USR01493,44,Male,Working Professional,Single,Instagram,4.3,4,3,No,...,7.3,7.5,7.1,5.6,4.7,7.2,1.7,2.5,6.9,Moderate
1493,USR01494,16,Male,Student,Single,YouTube,3.9,3,4,Yes,...,3.4,7.4,5.8,7.9,5.6,6.8,3.4,3.7,7.4,Moderate
1494,USR01495,27,Female,Student,In a Relationship,Instagram,7.9,2,8,Yes,...,4.9,2.6,8.1,4.9,5.4,10.0,1.5,2.0,6.8,Moderate
1495,USR01496,40,Male,Working Professional,In a Relationship,TikTok,2.7,2,4,No,...,3.3,7.4,8.5,6.7,4.5,7.6,2.3,2.3,6.5,High
1496,USR01497,23,Non-binary,Student,Married,YouTube,3.5,3,6,Yes,...,4.2,1.9,7.2,6.9,7.2,NaN,2.8,2.0,6.4,Moderate
1497,USR01498,39,Female,Student,Single,Instagram,5.3,2,3,Yes,...,0.4,2.4,5.1,NaN,6.4,7.8,2.6,4.8,4.7,Severe
1498,USR01499,26,Female,Freelancer,Single,Twitter/X,7.3,4,0,Yes,...,7.5,6.6,6.4,4.2,9.1,6.4,3.6,2.1,6.4,High
1499,USR01500,16,Female,Working Professional,In a Relationship,TikTok,0.7,3,2,No,...,5.9,8.5,5.3,7.2,3.4,2.3,3.9,3.1,6.1,Moderate

In [ ]:
df.shape

(1500, 30)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1500 entries, 0 to 1499
Data columns (total 30 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   User_ID                       1500 non-null   object
 1   Age                           1500 non-null   int64
 2   Gender                        1447 non-null   object
 3   Occupation                    1455 non-null   object
 4   Relationship_Status           1449 non-null   object
 5   Primary_Platform              1447 non-null   object
 6   Daily_Usage_Hours             1444 non-null   float64
 7   Platforms_Used_Count          1500 non-null   int64
 8   Posts_Per_Week                1500 non-null   int64
 9   Late_Night_Usage              1450 non-null   object
 10  First_Check_Morning           1500 non-null   object
 11  Notifications_Per_Day         1500 non-null   int64
 12  FOMO_Score                    1445 non-null   float64
 13  Social_Comparison_Score       1449 non-null   float64
 14  Validation_Seeking_Score      1442 non-null   float64
 15  Scroll_Without_Purpose        1500 non-null   float64
 16  Tried_To_Cut_Back             1459 non-null   object
 17  Failed_To_Cut_Back            1457 non-null   object
 18  Anxiety_Score                 1452 non-null   float64
 19  Depression_Score              1445 non-null   float64
 20  Loneliness_Score              1445 non-null   float64
 21  Self_Esteem_Score             1431 non-null   float64
 22  Sleep_Quality_Score           1432 non-null   float64
 23  Sleep_Hours                   1438 non-null   float64
 24  Productivity_Loss_Score       1449 non-null   float64
 25  Offline_Relationship_Quality  1430 non-null   float64
 26  Physical_Activity_Hrs_Week    1449 non-null   float64
 27  Screen_Free_Time_Hrs          1440 non-null   float64
 28  Mental_Wellbeing_Score        1500 non-null   float64
 29  Addiction_Level               1500 non-null   object
dtypes: float64(16), int64(4), object(10)
memory usage: 351.7+ KB

In [ ]:
df.describe()

,Age,Daily_Usage_Hours,Platforms_Used_Count,Posts_Per_Week,Notifications_Per_Day,FOMO_Score,Social_Comparison_Score,Validation_Seeking_Score,Scroll_Without_Purpose,Anxiety_Score,Depression_Score,Loneliness_Score,Self_Esteem_Score,Sleep_Quality_Score,Sleep_Hours,Productivity_Loss_Score,Offline_Relationship_Quality,Physical_Activity_Hrs_Week,Screen_Free_Time_Hrs,Mental_Wellbeing_Score
count,1500.000000,1444.000000,1500.000000,1500.000000,1500.000000,1445.000000,1449.000000,1442.000000,1500.000000,1452.000000,1445.000000,1445.000000,1431.000000,1432.000000,1438.000000,1449.000000,1430.000000,1449.000000,1440.000000,1500.000000
mean,29.372000,4.521399,3.236000,3.936000,60.244667,5.445882,5.495514,5.013107,5.449867,5.110537,4.562630,4.484429,5.519846,5.508659,6.557580,5.026570,5.482797,3.016494,3.025903,6.429733
std,8.550459,2.108319,1.682714,1.948273,33.150688,2.183914,2.041919,2.112417,2.083848,2.157587,2.199201,1.997623,1.993134,1.997842,1.380144,2.114049,2.045514,1.715963,1.691351,1.299288
min,15.000000,0.500000,1.000000,0.000000,5.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.000000,0.000000,0.000000,0.000000,0.000000,1.500000
25%,22.000000,3.100000,2.000000,3.000000,36.000000,4.000000,4.100000,3.600000,4.000000,3.700000,3.100000,3.100000,4.200000,4.100000,5.600000,3.600000,4.100000,1.800000,1.800000,5.500000
50%,29.000000,4.400000,3.000000,4.000000,59.000000,5.500000,5.500000,5.000000,5.500000,5.100000,4.500000,4.500000,5.600000,5.500000,6.600000,5.000000,5.400000,3.000000,3.000000,6.400000
75%,37.000000,5.900000,4.000000,5.000000,81.250000,7.000000,6.900000,6.500000,6.900000,6.600000,6.000000,5.900000,6.900000,6.900000,7.500000,6.400000,7.000000,4.200000,4.200000,7.300000
max,44.000000,12.000000,8.000000,12.000000,165.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,8.900000,10.300000,10.000000

In [ ]:
df.columns

Index(['User_ID', 'Age', 'Gender', 'Occupation', 'Relationship_Status',
       'Primary_Platform', 'Daily_Usage_Hours', 'Platforms_Used_Count',
       'Posts_Per_Week', 'Late_Night_Usage', 'First_Check_Morning',
       'Notifications_Per_Day', 'FOMO_Score', 'Social_Comparison_Score',
       'Validation_Seeking_Score', 'Scroll_Without_Purpose',
       'Tried_To_Cut_Back', 'Failed_To_Cut_Back', 'Anxiety_Score',
       'Depression_Score', 'Loneliness_Score', 'Self_Esteem_Score',
       'Sleep_Quality_Score', 'Sleep_Hours', 'Productivity_Loss_Score',
       'Offline_Relationship_Quality', 'Physical_Activity_Hrs_Week',
       'Screen_Free_Time_Hrs', 'Mental_Wellbeing_Score', 'Addiction_Level'],
      dtype='object')

In [ ]:
df.dtypes

User_ID                          object
Age                               int64
Gender                           object
Occupation                       object
Relationship_Status              object
Primary_Platform                 object
Daily_Usage_Hours               float64
Platforms_Used_Count              int64
Posts_Per_Week                    int64
Late_Night_Usage                 object
First_Check_Morning              object
Notifications_Per_Day             int64
FOMO_Score                      float64
Social_Comparison_Score         float64
Validation_Seeking_Score        float64
Scroll_Without_Purpose          float64
Tried_To_Cut_Back                object
Failed_To_Cut_Back               object
Anxiety_Score                   float64
Depression_Score                float64
Loneliness_Score                float64
Self_Esteem_Score               float64
Sleep_Quality_Score             float64
Sleep_Hours                     float64
Productivity_Loss_Score         float64
Offline_Relationship_Quality    float64
Physical_Activity_Hrs_Week      float64
Screen_Free_Time_Hrs            float64
Mental_Wellbeing_Score          float64
Addiction_Level                  object
dtype: object

In [ ]:
df.index

RangeIndex(start=0, stop=1500, step=1)

In [ ]:
df.size

45000

In [ ]:
df["Age"].unique()

array([30, 19, 40, 37, 18, 34, 38, 22, 43, 29, 23, 25, 41, 21, 31, 27, 15,
       26, 20, 39, 36, 42, 44, 17, 24, 16, 32, 33, 35, 28])

In [ ]:
df["Age"].nunique()

30

In [ ]:
df["Age"]

0       30
1       19
2       40
3       37
4       18
        ..
1495    40
1496    23
1497    39
1498    26
1499    16
Name: Age, Length: 1500, dtype: int64

In [ ]:
df[["Age", "Gender"]]

      Age      Gender
0      30        Male
1      19        Male
2      40        Male
3      37      Female
4      18  Non-binary
...   ...         ...
1495   40        Male
1496   23  Non-binary
1497   39      Female
1498   26      Female
1499   16      Female

[1500 rows x 2 columns]

In [ ]:
df.loc[2, "Age"]

np.int64(40)

In [ ]:
df.iloc[2,0]

'USR00003'

In [ ]:
df.loc[0]

User_ID                                     USR00001
Age                                               30
Gender                                          Male
Occupation                      Working Professional
Relationship_Status                In a Relationship
Primary_Platform                             YouTube
Daily_Usage_Hours                                2.9
Platforms_Used_Count                               4
Posts_Per_Week                                     3
Late_Night_Usage                                  No
First_Check_Morning                     Within 5 min
Notifications_Per_Day                             62
FOMO_Score                                       4.9
Social_Comparison_Score                          7.4
Validation_Seeking_Score                         2.1
Scroll_Without_Purpose                          10.0
Tried_To_Cut_Back                                 No
Failed_To_Cut_Back                                No
Anxiety_Score                                    2.5
Depression_Score                                 3.8
Loneliness_Score                                 1.7
Self_Esteem_Score                                6.5
Sleep_Quality_Score                              8.5
Sleep_Hours                                      5.3
Productivity_Loss_Score                          3.7
Offline_Relationship_Quality                     3.8
Physical_Activity_Hrs_Week                       5.8
Screen_Free_Time_Hrs                             3.1
Mental_Wellbeing_Score                           7.3
Addiction_Level                                  Low
Name: 0, dtype: object

In [ ]:
df.iloc[0]

User_ID                                     USR00001
Age                                               30
Gender                                          Male
Occupation                      Working Professional
Relationship_Status                In a Relationship
Primary_Platform                             YouTube
Daily_Usage_Hours                                2.9
Platforms_Used_Count                               4
Posts_Per_Week                                     3
Late_Night_Usage                                  No
First_Check_Morning                     Within 5 min
Notifications_Per_Day                             62
FOMO_Score                                       4.9
Social_Comparison_Score                          7.4
Validation_Seeking_Score                         2.1
Scroll_Without_Purpose                          10.0
Tried_To_Cut_Back                                 No
Failed_To_Cut_Back                                No
Anxiety_Score                                    2.5
Depression_Score                                 3.8
Loneliness_Score                                 1.7
Self_Esteem_Score                                6.5
Sleep_Quality_Score                              8.5
Sleep_Hours                                      5.3
Productivity_Loss_Score                          3.7
Offline_Relationship_Quality                     3.8
Physical_Activity_Hrs_Week                       5.8
Screen_Free_Time_Hrs                             3.1
Mental_Wellbeing_Score                           7.3
Addiction_Level                                  Low
Name: 0, dtype: object

# PANDAS (DAY 2)